### ISSUE TITLE
Update version?

### ISSUE THREAD

**Issue by QianFuv** [coco875/noisium-forge#2]
The new version has fixed a lot of bugs and improved performance. Is it possible to backport these changes to 1.19.2?

**Comment by coco875** [comment]
1.19.2 are depreciate for a while by forge and the origine of this project it was more for a personal modpack so since I don't do anything else in 1.19.2 any sync with the master branch are planned

**Comment by QianFuv** [comment]
Okay, but I believe maintaining synchronization with upstream will benefit all users who use this mod, as the optimization brought by this mod is a bit too obvious.

**Comment by coco875** [comment]
yeah but a lot of mod are no longer maintain in 1.19.2 so I don't see the point to update it, if you want you can do it or make a fork
